// @vitest-environment node
//
// Dart↔JavaScript parity for the compiled domain module (issue #1251).
//
// `webapp/test/domain/fixtures.json` is generated by the Dart side
// (`dart run tool/web_domain/generate_fixtures.dart`) and committed; the
// Dart pinning test (`test/domain/web_domain_fixtures_test.dart`) fails
// when the domain's output drifts from it. THIS suite runs every fixture
// case through the **compiled dart2js module** and fails when the module's
// output drifts from the same file — so Dart and JavaScript are pinned to
// each other through the committed middle. Every output also passes
// through the client's Zod schemas, proving the shapes the UI will
// consume.
//
// Requires the module to be built first (CI does this before `npm test`;
// see webapp/README.md):
//   dart compile js -O2 tool/web_domain/main.dart \
//     -o webapp/public/domain/lunarlog_domain.js

import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { expect, describe, it } from 'vitest';
import type { z } from 'zod';

import { DomainCallError, callDomain } from '../../src/domain/client';
import {
  bbtChartSchema,
  calendarForecastSchema,
  cycleRecapResponseSchema,
  cycleHistoryViewSchema,
  dateValidationSchema,
  exportDocumentSchema,
  insightsReportSchema,
  inviteLinkSchema,
  predictionSchema,
  todayLogSchema,
} from '../../src/domain/schemas';
import { loadDomainModule } from './load-module';

interface FixtureCase {
  name: string;
  method: string;
  request: Record<string, unknown>;
  expected: { ok: true; data: unknown };
}

const fixtures: FixtureCase[] = JSON.parse(
  readFileSync(join(import.meta.dirname, 'fixtures.json'), 'utf8'),
);

/** Method → the Zod schema the client validates that method's data with. */
const schemas: Record<string, z.ZodType<unknown>> = {
  predict: predictionSchema,
  cycleHistory: cycleHistoryViewSchema,
  insights: insightsReportSchema,
  bbtChart: bbtChartSchema,
  cycleRecap: cycleRecapResponseSchema,
  calendarForecast: calendarForecastSchema,
  validateDayEntryDate: dateValidationSchema,
  buildExport: exportDocumentSchema,
  parseInviteLink: inviteLinkSchema.nullable(),
  todayLog: todayLogSchema,
};

/** Structural equality with numeric tolerance for Dart's `29.0` vs JS's `29`. */
function deepEq(a: unknown, b: unknown): boolean {
  if (typeof a === 'number' && typeof b === 'number') return Object.is(a, b);
  if (a === null || b === null || typeof a !== 'object' || typeof b !== 'object')
    return a === b;
  if (Array.isArray(a) && Array.isArray(b)) {
    return a.length === b.length && a.every((value, i) => deepEq(value, b[i]));
  }
  if (Array.isArray(a) || Array.isArray(b)) return false;
  const aRec = a as Record<string, unknown>;
  const bRec = b as Record<string, unknown>;
  const aKeys = Object.keys(aRec);
  return (
    aKeys.length === Object.keys(bRec).length &&
    aKeys.every((key) => key in bRec && deepEq(aRec[key], bRec[key]))
  );
}

describe('compiled domain module parity (issue #1251)', () => {
  const module = loadDomainModule();

  it('exposes the facade version', () => {
    expect(module.version).toBe('1');
  });

  for (const fixture of fixtures) {
    it(`parity: ${fixture.name}`, () => {
      const schema: z.ZodType<unknown> | undefined = schemas[fixture.method];
      expect(schema, `no schema registered for ${fixture.method}`).toBeDefined();

      // Through the same client entry point the UI uses: envelope unwrap
      // AND Zod validation both apply, so a shape drift fails here even
      // before the value comparison.
      const data = callDomain(module, fixture.method, fixture.request, schema);
      expect(deepEq(data, fixture.expected.data)).toBe(true);
    });
  }

  it('surfaces the error envelope as DomainCallError', () => {
    expect(() => callDomain(module, 'teleport', {}, predictionSchema)).toThrow(DomainCallError);
  });

  it('times the #710 seeded 18-month shape (spike: <50 ms bar)', () => {
    const seed = fixtures.find((fixture) => fixture.name === 'seed18m.predict');
    expect(seed).toBeDefined();
    const request = JSON.stringify(seed!.request);
    for (let i = 0; i < 25; i++) module.invoke('predict', request); // warm-up
    const times: number[] = [];
    for (let i = 0; i < 100; i++) {
      const start = performance.now();
      module.invoke('predict', request);
      times.push(performance.now() - start);
    }
    times.sort((a, b) => a - b);
    const p95 = times[95];
    // Sanity bound only — CI runners vary; the spike's real number lives
    // in the PR. A order-of-magnitude regression (the bar is 50 ms) fails.
    expect(p95, `p95 ${p95.toFixed(2)}ms per prediction on the 18-month shape`).toBeLessThan(
      50,
    );
    console.log(
      `seed18m predict: p50 ${times[50].toFixed(3)}ms p95 ${p95.toFixed(3)}ms ` +
        `max ${times[times.length - 1].toFixed(3)}ms over 100 runs`,
    );
  });
});
