#!/usr/bin/env bash
set -euo pipefail

# .github/scripts/tests/apple-client-secret.test.sh (Issue #974)
#
# Covers .github/scripts/apple-client-secret.sh, including a real
# cryptographic check of the minted JWT. The signing key is generated by the
# test itself (a throwaway P-256 key under mktemp) - the production `.p8` is
# never read, and the minted token is never logged.
#
# Run with:
#
#   bash .github/scripts/tests/apple-client-secret.test.sh

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPT="$SCRIPT_DIR/../apple-client-secret.sh"
# shellcheck source=lib/assert.sh
source "$SCRIPT_DIR/lib/assert.sh"

TMP="$(mktemp -d "${TMPDIR:-/tmp}/apple-client-secret-test.XXXXXX")"
trap 'rm -rf "$TMP"' EXIT

openssl ecparam -name prime256v1 -genkey -noout -out "$TMP/key.pem" 2>/dev/null
openssl ec -in "$TMP/key.pem" -pubout -out "$TMP/pub.pem" 2>/dev/null
# A second, unrelated key to prove the signature check is not vacuous.
openssl ecparam -name prime256v1 -genkey -noout -out "$TMP/other-key.pem" 2>/dev/null
openssl ec -in "$TMP/other-key.pem" -pubout -out "$TMP/other-pub.pem" 2>/dev/null

export APPLE_TEAM_ID=TEAM123
export APPLE_KEY_ID=KEYABC
export APPLE_SERVICES_ID=com.wjdavis5.lunarlog.web
export APPLE_PRIVATE_KEY
APPLE_PRIVATE_KEY="$(cat "$TMP/key.pem")"

# --- base64url helpers for independently verifying the token ---------------

b64url_to_hex() {
  local s
  s="$(cat | tr '_-' '/+')"
  case $(( ${#s} % 4 )) in
    2) s="$s==" ;;
    3) s="$s=" ;;
  esac
  printf '%s' "$s" | openssl base64 -d -A | od -An -v -tx1 | tr -d ' \n'
}

b64url_to_json() {
  local s
  s="$(cat | tr '_-' '/+')"
  case $(( ${#s} % 4 )) in
    2) s="$s==" ;;
    3) s="$s=" ;;
  esac
  printf '%s' "$s" | openssl base64 -d -A
}

# One DER INTEGER TLV: `02 <len> <minimal big-endian bytes>`, prepending the
# 0x00 sign byte when the high bit is set.
der_int_hex() {
  local h="$1"
  while [ "${h#00}" != "$h" ] && [ "${#h}" -gt 2 ]; do h="${h#00}"; done
  case "$h" in
    8*|9*|[a-fA-F]*) h="00$h" ;;
  esac
  printf '02%02x%s' "$(( ${#h} / 2 ))" "$h"
}

hex_to_file() {
  local hex="$1" f="$2" esc="" i=0
  while [ "$i" -lt "${#hex}" ]; do
    esc="$esc\\x${hex:$i:2}"
    i=$((i + 2))
  done
  printf '%b' "$esc" > "$f"
}

# Converts the JWS raw `r || s` signature back to DER and verifies it with
# OpenSSL - an independent check that the script's DER -> raw conversion is
# correct and that the signature is real, not merely well-shaped.
verify_jwt_signature() {
  local token="$1" pub="$2"
  local signing sig_b64 raw r s content der
  signing="$(printf '%s' "$token" | cut -d. -f1,2)"
  sig_b64="$(printf '%s' "$token" | cut -d. -f3)"
  raw="$(printf '%s' "$sig_b64" | b64url_to_hex)"
  [ "${#raw}" -eq 128 ] || return 1
  r="${raw:0:64}"
  s="${raw:64:64}"
  content="$(der_int_hex "$r")$(der_int_hex "$s")"
  der="30$(printf '%02x' $(( ${#content} / 2 )))$content"
  hex_to_file "$der" "$TMP/verify.der"
  printf '%s' "$signing" | openssl dgst -sha256 -verify "$pub" -signature "$TMP/verify.der" >/dev/null 2>&1
}

# --- mint: structure, claims, and a real signature check -------------------

token="$(bash "$SCRIPT" mint)"

assert_eq "mint produces a three-segment JWT" "3" "$(printf '%s' "$token" | awk -F. '{print NF}')"
case "$token" in
  *[[:space:]]*) token_has_space=yes ;;
  *) token_has_space=no ;;
esac
assert_eq "mint output is a single token with no whitespace" "no" "$token_has_space"
assert_not_contains "mint never prints the private key" "$token" "BEGIN PRIVATE KEY"

assert_eq "the JWT's sub claim is the Services ID" \
  "com.wjdavis5.lunarlog.web" "$(printf '%s' "$token" | bash "$SCRIPT" jwt-claim sub)"
assert_eq "the JWT's aud claim is Apple" \
  "https://appleid.apple.com" "$(printf '%s' "$token" | bash "$SCRIPT" jwt-claim aud)"
assert_eq "the JWT's iss claim is the team id" \
  "TEAM123" "$(printf '%s' "$token" | bash "$SCRIPT" jwt-claim iss)"

header_json="$(printf '%s' "$token" | cut -d. -f1 | b64url_to_json)"
assert_eq "the JWT header alg is ES256" "ES256" "$(printf '%s' "$header_json" | jq -r .alg)"
assert_eq "the JWT header kid is the key id" "KEYABC" "$(printf '%s' "$header_json" | jq -r .kid)"

iat="$(printf '%s' "$token" | bash "$SCRIPT" jwt-claim iat)"
exp="$(printf '%s' "$token" | bash "$SCRIPT" jwt-claim exp)"
assert_eq "exp is iat plus (TTL - margin) days" \
  "$(( iat + 175 * 86400 ))" "$exp"

if verify_jwt_signature "$token" "$TMP/pub.pem"; then sig_result=ok; else sig_result=fail; fi
assert_eq "the minted JWT signature verifies against the throwaway public key" "ok" "$sig_result"

if verify_jwt_signature "$token" "$TMP/other-pub.pem"; then other_result=ok; else other_result=fail; fi
assert_eq "the signature does not verify under a different key" "fail" "$other_result"

# --- mint: APPLE_SERVICES_ID is mandatory ----------------------------------

set +e
services_err="$(APPLE_SERVICES_ID= bash "$SCRIPT" mint 2>&1 1>/dev/null)"
services_rc=$?
set -e
assert_eq "mint fails when APPLE_SERVICES_ID is unset" "1" "$services_rc"
assert_contains "the failure names APPLE_SERVICES_ID" "$services_err" "APPLE_SERVICES_ID"

# --- jwt-claim: never fails a caller on a non-JWT --------------------------

assert_eq "jwt-claim prints nothing for a non-JWT" "" \
  "$(printf 'not-a-jwt' | bash "$SCRIPT" jwt-claim sub)"

# --- client-id: reads the current value, never drops an entry --------------

assert_eq "client-id adds the Services ID to a bundle-id-only value" \
  "com.wjdavis5.lunarlog,com.wjdavis5.lunarlog.web" \
  "$(bash "$SCRIPT" client-id 'com.wjdavis5.lunarlog')"
assert_eq "client-id leaves an already-complete value unchanged" \
  "com.wjdavis5.lunarlog,com.wjdavis5.lunarlog.web" \
  "$(bash "$SCRIPT" client-id 'com.wjdavis5.lunarlog,com.wjdavis5.lunarlog.web')"
assert_eq "client-id preserves an unrelated extra entry" \
  "com.wjdavis5.lunarlog,com.example.other,com.wjdavis5.lunarlog.web" \
  "$(bash "$SCRIPT" client-id 'com.wjdavis5.lunarlog,com.example.other,com.wjdavis5.lunarlog.web')"
assert_eq "client-id tolerates spaces around entries" \
  "com.wjdavis5.lunarlog,com.wjdavis5.lunarlog.web" \
  "$(bash "$SCRIPT" client-id 'com.wjdavis5.lunarlog , com.wjdavis5.lunarlog.web')"
assert_eq "client-id builds both ids from an empty value" \
  "com.wjdavis5.lunarlog,com.wjdavis5.lunarlog.web" \
  "$(bash "$SCRIPT" client-id '')"
assert_eq "client-id adds the bundle id when only the Services ID is set" \
  "com.wjdavis5.lunarlog,com.wjdavis5.lunarlog.web" \
  "$(bash "$SCRIPT" client-id 'com.wjdavis5.lunarlog.web')"

# --- staleness: the missed-rotation signal ---------------------------------

assert_eq "staleness is fresh with no prior successful run" \
  "fresh" "$(bash "$SCRIPT" staleness - 1000000 180)"
assert_eq "staleness is fresh just inside the window" \
  "fresh" "$(bash "$SCRIPT" staleness 1000000 $(( 1000000 + 100 * 86400 )) 180)"
assert_eq "staleness is overdue just past the window" \
  "overdue" "$(bash "$SCRIPT" staleness 1000000 $(( 1000000 + 181 * 86400 )) 180)"
assert_eq "staleness is overdue for a badly missed schedule" \
  "overdue" "$(bash "$SCRIPT" staleness 1000000 $(( 1000000 + 300 * 86400 )) 180)"

print_summary "apple-client-secret.test.sh"
