// Build-time generators for the React web client (issue #1249).
//
//   npm run generate          (wired into predev/prebuild)
//   node scripts/generate.mjs
//
// Two committed artifacts are regenerated from sources that live outside
// webapp/:
//
//   1. src/i18n/messages.en.json + src/i18n/message-ids.ts
//      The FormatJS message catalogue, generated from the app's
//      `lib/l10n/app_en.arb` — the same single home for user-facing copy the
//      Flutter app translates from (`tool/export_help_cards.dart` feeds the
//      marketing site the same way). No user-facing string is typed in TSX;
//      eslint.config.js's copy ban enforces that, and this catalogue is what
//      `t()` reads.
//
//   2. src/theme/tokens.css
//      CSS custom properties derived from `src/theme/tokens.generated.json`
//      (the app theme export produced by
//      `flutter test tool/export_webapp_tokens_generate_test.dart`). So the
//      web client never hand-copies a hex value: styles reference
//      `var(--ll-…)` only, and test/tokens.test.ts scans the hand-written
//      CSS for any literal colour.
//
// Both artifacts are committed so a stale copy is a visible PR diff, and
// test/messages.test.ts re-runs these builders in memory to fail when they
// drift — the freshness discipline CI applies to db.g.dart and to the site's
// help-cards export.
//
// Deterministic: catalogue and CSS follow the arb's and the JSON's own key
// order, so two runs on the same inputs produce byte-identical output.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
export const webappRoot = resolve(here, '..');
export const repoRoot = resolve(webappRoot, '..');

export const arbPath = join(repoRoot, 'lib', 'l10n', 'app_en.arb');
export const messagesOutPath = join(webappRoot, 'src', 'i18n', 'messages.en.json');
export const messageIdsOutPath = join(webappRoot, 'src', 'i18n', 'message-ids.ts');
export const tokensJsonPath = join(webappRoot, 'src', 'theme', 'tokens.generated.json');
export const tokensCssOutPath = join(webappRoot, 'src', 'theme', 'tokens.css');

/** Reads the arb and returns the `{ id: message }` catalogue in arb order. */
export function buildMessageCatalogue(arbJson) {
  const arb = arbJson ?? JSON.parse(readFileSync(arbPath, 'utf8'));
  const catalogue = {};
  for (const key of Object.keys(arb)) {
    if (key.startsWith('@')) continue; // `@key` metadata and `@@locale`
    if (typeof arb[key] !== 'string') {
      throw new Error(`lib/l10n/app_en.arb: '${key}' is not a string message`);
    }
    catalogue[key] = arb[key];
  }
  return catalogue;
}

/** Serialises the catalogue the way the committed file is formatted. */
export function serializeMessageCatalogue(catalogue) {
  return `${JSON.stringify(catalogue, null, 2)}\n`;
}

/** Builds the generated `message-ids.ts` source from the catalogue. */
export function buildMessageIdsModule(catalogue) {
  const ids = Object.keys(catalogue);
  const lines = [
    '// Generated by webapp/scripts/generate.mjs from lib/l10n/app_en.arb — do not edit.',
    '// Regenerate with `npm run generate` (webapp/).',
    '',
    'export const MESSAGE_IDS = [',
    ...ids.map((id) => `  ${JSON.stringify(id)},`),
    '] as const;',
    '',
    'export type MessageId = (typeof MESSAGE_IDS)[number];',
    '',
  ];
  return lines.join('\n');
}

// Kebab-cases a token name for CSS. Splits both camelCase (`onPrimary` →
// `on-primary`) and letter→digit boundaries (`space3` → `space-3`) — the
// second is what `global.css` reads (`var(--ll-space-3)`, issue #1271), so
// `e1` becomes `--ll-e-1` the same mechanical way.
function kebab(name) {
  return name
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/([a-zA-Z])(\d)/g, '$1-$2')
    .toLowerCase();
}

/**
 * Formats one Type-ramp slot as CSS custom property lines (2-space indent).
 * The slot's `fontFamily` names a family; the custom property it references
 * must be one of the two role variables this file actually defines
 * (`--ll-font-text`/`--ll-font-display`, issue #1271) — never a bare family
 * name like the `--ll-font-fraunces` the first cut emitted.
 */
function typeSlotVars(slotName, slot, indent, fonts) {
  const var_ = (suffix) => `--ll-type-${kebab(slotName)}-${suffix}`;
  const lines = [
    `${var_('font-size')}: ${slot.fontSize}px;`,
    `${var_('line-height')}: ${slot.lineHeight}px;`,
  ];
  if (slot.fontWeight !== null) lines.push(`${var_('font-weight')}: ${slot.fontWeight};`);
  if (slot.letterSpacing !== null)
    lines.push(`${var_('letter-spacing')}: ${slot.letterSpacing}px;`);
  if (slot.tabularFigures) lines.push(`${var_('font-variant-numeric')}: tabular-nums;`);
  const familyRole =
    slot.fontFamily === fonts.display
      ? 'display'
      : slot.fontFamily === fonts.text
        ? 'text'
        : null;
  if (familyRole === null) {
    throw new Error(
      `type slot '${slotName}': font family '${slot.fontFamily}' is neither ` +
        `fonts.text ('${fonts.text}') nor fonts.display ('${fonts.display}')`,
    );
  }
  lines.push(`${var_('font-family')}: var(--ll-font-${familyRole});`);
  return lines.map((l) => `${indent}${l}`);
}

function schemeVars(scheme, indent) {
  return Object.entries(scheme).map(([role, hex]) => `${indent}--ll-${kebab(role)}: ${hex};`);
}

// The calendar palette slots (issue #1253) sit in their own `--ll-cal-`
// namespace so a hand-written rule can tell `--ll-cal-flow-heavy` from the
// M3 roles.
function calendarVars(scheme, indent) {
  return Object.entries(scheme).map(
    ([slot, hex]) => `${indent}--ll-cal-${kebab(slot)}: ${hex};`,
  );
}

/** Builds the full generated tokens.css content. */
export function buildTokensCss(tokens) {
  const spaceLines = Object.entries(tokens.space).map(
    ([name, px]) => `  --ll-${kebab(name)}: ${px}px;`,
  );
  const radiusLines = Object.entries(tokens.radius).map(
    ([name, px]) => `  --ll-${kebab(name)}: ${px}px;`,
  );
  const elevationLines = Object.entries(tokens.elevation).map(
    ([name, px]) => `  --ll-${kebab(name)}: ${px}px;`,
  );
  const motionLines = Object.entries(tokens.motion).map(
    ([name, ms]) => `  --ll-${kebab(name)}: ${ms}ms;`,
  );
  const fontLines = [
    `  --ll-font-text: '${tokens.fonts.text}', system-ui, sans-serif;`,
    `  --ll-font-display: '${tokens.fonts.display}', serif;`,
  ];
  const typeLines = Object.entries(tokens.type).flatMap(([name, slot]) =>
    typeSlotVars(name, slot, '  ', tokens.fonts),
  );

  const block = (title, lines) => ['/*', ` * ${title}`, ' */', ...lines, ''];
  // Section comments live *inside* the rule: a custom property outside any
  // rule block is dropped by every browser (issue #1271), so the non-colour
  // tokens share one `:root` and the old bare top-level declarations are gone.
  const section = (title, lines) => [`  /* ${title} */`, ...lines, ''];

  return [
    // CSS has no `//` line comments — the first cut's `// Generated by …`
    // header parsed as one invalid selector that swallowed the light-scheme
    // `:root` with it (issue #1271). Block comments only.
    '/*',
    ' * Generated by webapp/scripts/generate.mjs from src/theme/tokens.generated.json',
    ' * (the app-theme export) — do not edit. Regenerate with `npm run generate`.',
    ' * Design tokens only: hand-written CSS must reference these variables and',
    ' * never a literal colour (test/tokens.test.ts scans for that).',
    ' */',
    '',
    // One dark media query total (test/tokens.test.ts pins the generated
    // sheet's structure): the M3 scheme roles and the #1253 calendar
    // palette each carry their own `:root` inside it.
    ...block(
      'Colour schemes — the resolved M3 roles and the calendar palette (LunarLogColors).',
      [
        ':root {',
        ...schemeVars(tokens.schemes.light, '  '),
        '}',
        '',
        ':root {',
        ...calendarVars(tokens.calendar.light, '  '),
        '}',
        '',
        '@media (prefers-color-scheme: dark) {',
        '  :root {',
        ...schemeVars(tokens.schemes.dark, '    '),
        '  }',
        '',
        '  :root {',
        ...calendarVars(tokens.calendar.dark, '    '),
        '  }',
        '}',
      ],
    ),
    ':root {',
    ...section('Fonts (bundled via @fontsource; the app theme’s two families).', fontLines),
    ...section('Spacing scale (LLSpace).', spaceLines),
    ...section('Corner radii (LLRadius).', radiusLines),
    ...section('Elevation steps (LLElevation).', elevationLines),
    ...section('Motion durations (LLMotion).', motionLines),
    ...section('Type ramp (LLType).', typeLines),
    '}',
    '',
  ].join('\n');
}

/** Reads tokens.generated.json from disk (or takes parsed JSON). */
export function loadTokens(tokensJson) {
  return tokensJson ?? JSON.parse(readFileSync(tokensJsonPath, 'utf8'));
}

function writeAll({ catalogue, tokens }) {
  const cat = catalogue ?? buildMessageCatalogue();
  const tok = loadTokens(tokens);
  const writes = [
    [messagesOutPath, serializeMessageCatalogue(cat)],
    [messageIdsOutPath, buildMessageIdsModule(cat)],
    [tokensCssOutPath, buildTokensCss(tok)],
  ];
  for (const [path, content] of writes) {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content, 'utf8');
    console.log(`Wrote ${path} (${content.length} bytes)`);
  }
}

const invokedDirectly =
  process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (invokedDirectly) {
  writeAll({});
}
